### PR TITLE
Specify dependency versions directly in Gemfile & gemspec

### PR DESCRIPTION
**Pull request by lavaturtle**
This replaces the Gemfile.lock file with dependency version declarations in the Gemfile and gemspec files.

This is the more correct way of doing it, because then applications using this gem can have useful information about which versions of dependencies are actually required. Also, it eliminates the recurring maintenance task of updating the Gemfile.lock regularly.

Q: If I work on this gem, will I still have a Gemfile.lock file locally?
A: Yes, containing versions that bundler installs based on the requirements. But it will not be committed to source control.

Also included: Updates `jeweler`, because the previous version did not work with modern versions of bundler.

I made the Gemfile changes here by hand, then ran `rake gemspec` to update the gemspec file. This rake task is provided by the `jeweler` gem.

### CODE REVIEW

**Comment by lavaturtle** [comment]
The CI failure appears to be related to a problem with a webmock stub. I haven't yet figured out how to get it working properly.

**Comment by lavaturtle** [comment]
I've determined that the upgrade of webmock from 1.21.0 to 3.1.1 in https://github.com/controlshift/tijuana_client/commit/a62395c1efd2b1c74fa0b2e2708bcc9079218764 broke the build. I'm reading the webmock changelog now to figure out how to update the specs so that they'll work with a modern version of webmock.

**Comment by lavaturtle** [comment]
The remaining build failure is, I think, because of a potential bug with basic auth in Vertebrae. Once https://github.com/controlshift/vertebrae/pull/2 is merged, we should update the vertebrae dependency here and see if it fixes the error.

**Review by anero — APPROVED** [review]
Looks good other than the same comment about `jeweler` from other gem

**Pull request merged**
